name: VoltskiyaWebserver
version: 1.0
main: apple.voltskiya.webroot.WebPlugin
api-version: 1.19
authors: [ appleptr16 ]
depend: [ LoadDependencies, VoltPluginManager, VoltskiyaUtilities, VoltskiyaMobSystem ]
